/** Chat (agentic) transport contracts and streaming client. */
export {
  CHAT_DOCUMENT_EXTENSIONS,
  CHAT_IMAGE_MIME_TYPES,
  CHAT_MAX_ATTACHMENTS,
  CHAT_MAX_DOCUMENT_BYTES,
  CHAT_MAX_PDF_BYTES,
  CHAT_MAX_IMAGE_BYTES,
  classifyChatAttachment,
  chatAttachmentContentUrl,
  createChatSession,
  deleteChatAttachment,
  deleteChatSession,
  fetchChatModels,
  fetchChatSession,
  fetchChatSessions,
  parseChatEventBlock,
  renameChatSession,
  sendChatMessage,
  uploadChatAttachment,
} from "../api";

export type {
  ChatAttachment,
  ChatAttachmentKind,
  ChatAttachmentStatus,
  ChatEvent,
  ChatMessageRecord,
  ChatMessageStatus,
  ChatModelListResponse,
  ChatModelOption,
  ChatSendMessagePayload,
  ChatSessionDetail,
  ChatSessionSummary,
  ChatSourceRef,
  ChatStreamHandlers,
} from "../api";
